name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test on Multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            java-version: 17
          - os: windows-latest
            java-version: 17
          - os: macos-latest
            java-version: 17

    steps:
      # Клонируем репозиторий
      - name: Checkout Code
        uses: actions/checkout@v3

      # Настраиваем JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      # Собираем проект
      - name: Build with Maven
        run: mvn clean package

      # Запускаем тесты
      - name: Run Tests
        run: mvn test

  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: env-actions-example

    steps:
      # Клонируем репозиторий
      - name: Checkout Code
        uses: actions/checkout@v3

      # Авторизация в Docker Hub с использованием токена
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Создаем Docker-образ
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:latest .

      # Загружаем образ в Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:latest

